<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf8" />
  
  {{ stylesheet_link("css/bootstrap.min.css") }}
  {{ stylesheet_link("css/bootstrap-theme.min.css") }}
  {{ stylesheet_link("css/style.css") }}
  
  {{ javascript_include("js/jquery-1.10.1.min.js") }}
  {{ javascript_include("js/bootstrap.min.js") }}
  {{ javascript_include("js/script.js") }}
</head>
<body>
	<div class="contain">
  	{% include "errors/messages.phtml" %}
		{% block content %} {% endblock %}
  </div>
</body>
</html>