<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf8" />
  
  {{ stylesheet_link("css/bootstrap.min.css") }}
  {{ stylesheet_link("css/bootstrap-theme.min.css") }}
  {{ stylesheet_link("css/style.css") }}
  
  {{ javascript_include("js/jquery-1.10.1.min.js") }}
  {{ javascript_include("js/bootstrap.min.js") }}
  {{ javascript_include("js/script.js") }}
</head>
<body>
	<div class="contain">
  		{% include "errors/messages.phtml" %}
		{% block content %} {% endblock %}
        <hr>
		<footer>
			<p><a href="https://github.com/mrspartak/phalconPasswordManager" target="_blank">Github project</a>. Made by <a href="http://assorium.ru" target="_blank">Assorium</a>

<!--LiveInternet counter--><script type="text/javascript"><!--
document.write("<a class='pull-right' href='http://www.liveinternet.ru/click' "+
"target=_blank><img src='//counter.yadro.ru/hit?t26.5;r"+
escape(document.referrer)+((typeof(screen)=="undefined")?"":
";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
";"+Math.random()+
"' alt='' title='LiveInternet: показано число посетителей за"+
" сегодня' "+
"border='0' width='88' height='15'><\/a>")
//--></script><!--/LiveInternet-->

            </p>
		</footer>
	</div>
</body>
</html>